microconf: fix mistetection of RHEL based platforms
Signed-off-by: Olaf Kirch <okir@suse.de>

diff --git a/microconf/stage3/02-pkg-config b/microconf/stage3/02-pkg-config
--- a/microconf/stage3/02-pkg-config
+++ b/microconf/stage3/02-pkg-config
@@ -44,4 +44,36 @@ function uc_pkg_config_find_highest_version {
 	done | tr . ' ' | sort -k1n -k2n -k3n | tr ' /' '. ' | tail -1
 }
 
+function uc_pkg_config_check_package {
 
+	pkgname=$1
+	if [ "$uc_with_pkg_config" != "yes" ]; then
+		uc_fatal "No pkg-config detected, unable to proceed ($pkgname)"
+	fi
+
+	echo -n "Detecting $pkgname version... "
+	export uc_with_$pkgname=
+
+	if ! pkg-config $pkgname; then
+		echo "not found" >&2
+		export uc_with_$pkgname=none
+		export uc_${pkgname}_libdir=
+		export uc_${pkgname}_incdir=
+		export uc_${pkgname}_cflags=
+		export uc_${pkgname}_libs=
+		export uc_define_have_${pkgname}=undef
+		return 1
+	fi
+
+	version="$(pkg-config --modversion $pkgname)"
+	echo "$version"
+
+	export uc_with_$pkgname="$version"
+	export uc_${pkgname}_libdir=$(pkg-config --variable libdir "$pkgname")
+	export uc_${pkgname}_incdir=$(pkg-config --variable includedir "$pkgname")
+	export uc_${pkgname}_cflags=$(pkg-config --cflags "$pkgname")
+	export uc_${pkgname}_libs=$(pkg-config --libs "$pkgname")
+	export uc_define_have_${pkgname}=define
+
+	return 0
+}
